server:
  error:
    include-message: always
    include-exception: on
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo-database
    username: demo-username
    password: demo-password

  jpa:
    hibernate:
      ddl-auto: update

springdoc:
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha

application:
  description: Test application to play with spring data and measure different ways of working with DB.
  contact:
    email: artemkaxboy@gmail.com
    url: https://github.com/artemkaxboy
    name: Artem Kolin
