server:
  error:
    include-message: always
    include-exception: on

spring:
#  datasource:
#    password: password
#    url: jdbc:postgresql://localhost:5432/database
#    username: username

  jpa:
    hibernate:
      ddl-auto: update

springdoc:
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha

application:
  name: Spring Data Showroom Application
  description: Test application to play with spring data and measure different ways of working with DB.
  contact:
    email: artemkaxboy@gmail.com
    url: https://github.com/artemkaxboy
    name: Artem Kolin
  version: 0.1-SNAPSHOT
