# Jobs to run on PR, tests, lint, check, etc.
name: Check commit

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:

  test-pr:
    name: Test PR
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ env.GITHUB_REF }}
          restore-keys: |
            ${{ runner.os }}-gradle-master
            ${{ runner.os }}-gradle-

      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Run tests
        # @doc https://github.com/eskatos/gradle-command-action
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: jacocoTestReport

      - uses: actions/upload-artifact@v2
        with:
          name: test-result
          path: ./build/reports/tests/test/
        if: always()

      - name: Upload coverage result
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report
