# Jobs to run on new release tag: publishing, documentation, final tests
name: Release

on:
  push:
    tags:
      - v*.*.*

jobs:

  publish:
    name: Publish final version
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-master
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set RELEASE_VERSION variable
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV

      - name: Publish docker image
        uses: eskatos/gradle-command-action@v1
        env:
          CONTAINER_REGISTRY_TOKEN: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}
        with:
          arguments: jib
