name: Release

on:
  push:
    tags:
      - v*.*
      - v*.*.*

jobs:

  create-github-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set RELEASE_VERSION variable
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: O_o
        env:
          CONTAINER_REGISTRY_TOKEN: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}
        run: echo ${CONTAINER_REGISTRY_TOKEN:0:10}

      - name: Publish docker image
        uses: eskatos/gradle-command-action@v1
        env:
          CONTAINER_REGISTRY_TOKEN: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}
        with:
          arguments: jib
          dependencies-cache-enabled: true
