# Jobs to run on new release tag: publishing, documentation, final tests
name: Release

on:
  push:
    tags:
      - v*.*.*
    branches:
      - healthcheck

jobs:

  publish:
    name: Publish final version
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-default
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set RELEASE_VERSION variable
        run: echo "ORG_GRADLE_PROJECT_applicationVersion=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV

      - name: Publish docker image
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: |
            jib -Djib.to.auth.username=${env.GITHUB_ACTOR} -Djib.to.auth.password=${secret.CONTAINER_REGISTRY_TOKEN} -Da=${ORG_GRADLE_PROJECT_applicationVersion}
