name: Check commit

on:
  pull_request:
    types: [opened, synchronize, reopened]

  push:
    branches:
      - "master"

jobs:

  tests:
    name: Test code
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Run tests
        # @doc https://github.com/eskatos/gradle-command-action
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: jacocoTestReport
          configuration-cache-enabled: true
#          dependencies-cache-enabled: true

      - uses: actions/upload-artifact@v2
        with:
          name: test-result
          path: ./build/reports/tests/test/
        if: always()

      - name: Upload coverage result
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report
