name: Release

on:
  push

jobs:

  create-github-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set RELEASE_VERSION variable
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - run: export
      - run: echo $GITHUB_REF
      - run: echo $RELEASE_VERSION
